CREATE DATABASE `user`;
SHOW DATABASES;
USE `user`;

CREATE TABLE `users` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`username` VARCHAR(45) NOT NULL UNIQUE,
`hash` VARCHAR(200) NOT NULL,
`salt` VARCHAR(100) NOT NULL,
`email` VARCHAR(50) NOT NULL,
`food` VARCHAR(50) NOT NULL DEFAULT('egg')
);

DESCRIBE users;
SELECT * FROM `users`;
