version: '1.0'
services:
  app:
    build: .
    container_name: my-camp
    ports:
      - "80:80"
    networks:
      - my-network-MySQL
    environment:
      HOST_SQL: container-MySQL
      MYSQL_USER: paul
      MYSQL_PASSWORD: paul123
      MYSQL_DATABASE: my_camp
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: container-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: my_camp
      MYSQL_USER: paul
      MYSQL_PASSWORD: paul123
    networks:
      - my-network-MySQL
    volumes:
      - ./seeds:/docker-entrypoint-initdb.d
      - ./data/MySQL:/var/lib/mysql


networks:
  my-network-MySQL:
    driver: bridge
