"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    "Camping is a form of outdoor recreation involving overnight stays with a basic temporary shelter such as a tent. Camping can also include a recreational vehicle, a permanent tent, a shelter such as a bivy or tarp, or no shelter at all. Typically, participants leave developed areas to spend time outdoors, in pursuit of activities providing them enjoyment or an educational experience. Spending the night away from home distinguishes camping from day-tripping, picnicking, and other outdoor activities.",
    "Camping as a recreational activity became popular among elites in the early 20th century. With time, it grew in popularity among other socioeconomic classes. Modern campers frequent publicly owned natural resources such as national and state parks, wilderness areas, and commercial campgrounds. In a few countries, such as Sweden and Scotland, public camping is legal on privately held land as well. Camping is a key part of many youth organizations around the world, such as Scouting, which use it to teach both self-reliance and teamwork.",
    "Camping describes a range of activities and approaches to outdoor accommodation. Survivalist and wild campers typically set off with as little as possible to get by. Other campers might use specialized camping gear designed to provide comfort, including their own power and heat sources as well as camping furniture. Camping may be combined with hiking, as in backpacking, and is often enjoyed in conjunction with other outdoor activities such as canoeing, kayaking, climbing, fishing, and hunting. Fastpacking involves both running and camping.",
    "The history of recreational camping is often traced back to Thomas Hiram Holding, a British travelling tailor, but it was actually first popularised in the UK on the river Thames. By the 1880s, large numbers of visitors took part in the pastime, which was connected to the late Victorian craze for pleasure boating.[2] Although Thomas Hiram Holding is often seen as the father of modern camping in the UK, he was responsible for popularising a different type of camping in the early twentieth century.",
    "The International Federation of Camping Clubs (Fédération Internationale de Camping et de Caravanning) was founded in 1932, with national clubs from many countries affiliating with it. By the 1960s, camping had become an established family holiday standard, and today campsites are widespread across Europe and North America.",
    "Survival camping involves certain items that campers are recommended to have with them in case something goes wrong and they need to be rescued. A survival kit includes mandatory items which are small and must fit in one's pocket or which otherwise could be carried on one's person. This kit is useless in these circumstances if it is kept in the backpack that is left in camp. Such a kit should include a small metal container which can be used to heat water over a campfire, a small length of duct tape which can prove useful in many situations, and an emergency space blanket.",
    "Candle stubs are good in starting a fire as well as in warming an enclosed space. One or two band-aids are mandatory in this type of camping. Any camper, and not only the survival ones, need waterproof matches or a lighter and a large safety pin or fish hook which can be used in fishing. Rubber gloves, antiseptic wipes, tinfoil, jackknife, or halazone tablets (which purify the water) are also to be included into a survival kit.",
    "Campers span a broad range of age, ability, and ruggedness, and campsites are designed in many ways as well. Many campgrounds have sites with facilities such as fire rings, barbecue grills, utilities, shared bathrooms and laundry, as well as access to nearby recreational facilities, however, not all campsites have similar levels of development.",
    "Campsites can range from a patch of dirt, to a level, paved pad with sewer and electricity with many public and private campgrounds also offering cabin options. (For more information on facilities, see the campsite and RV park articles.) Other vehicles used for camping include motorcycles, touring bicycles, boats, canoes, pack animals, and even bush planes; although backpacking on foot is a popular alternative.",
    "Tent camping sites often cost less than campsites with full amenities, and most allow direct access by car. Some walk-in sites lie a short walk away from the nearest road, but do not require full backpacking equipment. Those who seek a rugged experience in the outdoors prefer to camp with only tents, or with no shelter at all (under the stars).",
    "Canada is a country that has four different seasons throughout the year. In this day and age, with the proper camping equipment, it is possible to camp all over Canada all year around. At the end of the 19th century, Canada started establishing areas all over the territory to be later named National Parks. ",
    "Camping on open land, regardless of ownership, is legal in a few countries, including Sweden and Scotland. In Sweden, a right of public access – allowing outdoor recreational activity on privately held wilderness – is enshrined in the constitution.[22] Large groups, however, must obtain the landowner's permission.[23] In Scotland, people may camp on most unenclosed land, whether state- or privately owned. There is however a leave-no-trace policy and a common-law outdoor-access code."
];
